//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLC_数据采集系统_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODYINFOL200
    {
        public decimal ID { get; set; }
        public string DA { get; set; }
        public string TI { get; set; }
        public string FIS { get; set; }
        public string TYPE { get; set; }
        public string COLOR { get; set; }
        public string PRIMER { get; set; }
        public string SKID { get; set; }
        public string OFFSET { get; set; }
    }
}
